spring:
  application:
    name: springhl
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:ecommerce}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:r00t}
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  security:
#    user:
#      name: admin
#      password: admin