spring:
  application:
    name: springhl
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:ecommerce}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:r00t}
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    secret-key: a89c31e68731757d7100da93c2e301b36ee46383f8f951784bae6817ae8fa6c5d04882
    access-minutes: 5
    refresh-minutes: 7
  data:
    redis:
      host: localhost
      port: 6379
#  security:
#    user:
#      name: admin
#      password: admin